import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { TrendingUp, Target, Lightbulb, CheckCircle, ChevronRight, Sparkles, Brain, Flag } from 'lucide-react';
import PageLayout from '../../components/PageLayout';
import LoadingSpinner from '../../components/LoadingSpinner';
import api from '../../api/axios';

const icons = [Lightbulb, Target, TrendingUp, CheckCircle, Flag];

export default function GrowthSuggestions() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/student/growth-suggestions')
      .then(r => setData(r.data))
      .catch(() => setData(null))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <PageLayout><LoadingSpinner text="Crafting your growth strategy..." /></PageLayout>;

  return (
    <PageLayout>
      <header className="mb-10">
        <div className="flex items-center gap-3 mb-2">
            <span className="px-3 py-1 rounded-full bg-blue-50 text-blue-600 text-[10px] font-black uppercase tracking-widest">Personalized Roadmap</span>
        </div>
        <h1 className="text-4xl font-black text-slate-900 tracking-tighter">Growth <span className="text-blue-600">Strategy Plan</span></h1>
        <p className="text-slate-500 mt-2 font-medium">Actionable insights generated by our analysis model to elevate your potential.</p>
      </header>

      {!data ? (
        <div className="bg-white p-12 rounded-[2.5rem] border border-slate-100 shadow-sm text-center">
          <p className="text-slate-400 font-medium">Unable to generate a growth plan at this time.</p>
        </div>
      ) : (
        <div className="space-y-8">
          {/* Summary Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm group hover:border-blue-100 transition-all">
               <div className="flex items-center gap-3 mb-3">
                  <div className="w-8 h-8 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
                     <Target size={16} />
                  </div>
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Focus Area</span>
               </div>
               <p className="text-2xl font-black text-slate-900 capitalize leading-none">{data.weakest_skill}</p>
               <p className="text-xs text-slate-500 mt-2 font-medium">Primary improvement target</p>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm group hover:border-emerald-100 transition-all">
               <div className="flex items-center gap-3 mb-3">
                  <div className="w-8 h-8 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
                     <Brain size={16} />
                  </div>
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Competency</span>
               </div>
               <p className="text-2xl font-black text-slate-900 leading-none">{data.average_skill_score}/10</p>
               <p className="text-xs text-slate-500 mt-2 font-medium">Normalized skill average</p>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm group hover:border-amber-100 transition-all">
               <div className="flex items-center gap-3 mb-3">
                  <div className="w-8 h-8 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center">
                     <TrendingUp size={16} />
                  </div>
                  <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Reliability</span>
               </div>
               <p className="text-2xl font-black text-slate-900 leading-none">{Math.round(data.reliability * 100)}%</p>
               <p className="text-xs text-slate-500 mt-2 font-medium">Consistency index</p>
            </motion.div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
            {/* Growth Steps */}
            <div className="lg:col-span-8 space-y-6">
                <div className="flex justify-between items-center mb-6">
                   <h2 className="text-xl font-bold text-slate-900 flex items-center gap-2">
                       <Lightbulb className="text-blue-600" size={22} /> Recommended Milestones
                   </h2>
                   <span className="text-xs font-bold text-slate-400 uppercase">{data.growth_plan?.length} Steps Total</span>
                </div>

                <div className="space-y-4">
                  {data.growth_plan?.map((tip, i) => {
                    const colors = ['blue', 'emerald', 'amber', 'violet', 'rose'];
                    const color = colors[i % colors.length];
                    const Icon = icons[i % icons.length];
                    
                    const colorClasses = {
                        blue: 'bg-blue-50 text-blue-600 border-blue-100',
                        emerald: 'bg-emerald-50 text-emerald-600 border-emerald-100',
                        amber: 'bg-amber-50 text-amber-600 border-amber-100',
                        violet: 'bg-violet-50 text-violet-600 border-violet-100',
                        rose: 'bg-rose-50 text-rose-600 border-rose-100',
                    };

                    return (
                      <motion.div
                        key={i}
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: i * 0.1 }}
                        className="bg-white p-6 rounded-[2rem] border border-slate-100 shadow-sm hover:shadow-md transition-all flex items-start gap-6 relative group"
                      >
                        <div className={`shrink-0 w-12 h-12 rounded-2xl flex items-center justify-center border ${colorClasses[color]}`}>
                           <Icon size={22} />
                        </div>
                        <div className="flex-1">
                           <div className="flex items-center gap-2 mb-1">
                              <span className={`text-[10px] font-black uppercase tracking-widest ${colorClasses[color].split(' ')[1]}`}>Phase 0{i+1}</span>
                              <div className="flex-1 h-px bg-slate-50"></div>
                           </div>
                           <p className="text-slate-800 font-bold leading-relaxed">{tip}</p>
                        </div>
                        <div className="absolute right-6 top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity">
                           <div className="w-8 h-8 rounded-full bg-slate-50 flex items-center justify-center text-slate-300">
                              <ChevronRight size={16} />
                           </div>
                        </div>
                      </motion.div>
                    );
                  })}
                </div>
            </div>

            {/* Side Progress / Stats */}
            <div className="lg:col-span-4 space-y-8">
               <motion.div 
                initial={{ opacity: 0, scale: 0.9 }} 
                animate={{ opacity: 1, scale: 1 }} 
                transition={{ delay: 0.4 }} 
                className="bg-blue-600 p-8 rounded-[2.5rem] shadow-xl shadow-blue-500/20 text-white relative overflow-hidden"
              >
                  <Sparkles className="absolute top-4 right-4 text-blue-400 opacity-50" size={40} />
                  <h3 className="text-lg font-bold mb-6">Growth Readiness</h3>
                  
                  <div className="text-5xl font-black mb-2">{data.average_skill_score * 10}%</div>
                  <p className="text-blue-100 text-sm font-medium mb-8">Overall maturity score based on current skill synthesis.</p>
                  
                  <div className="h-2 bg-blue-500/50 rounded-full overflow-hidden">
                     <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: `${data.average_skill_score * 10}%` }}
                      transition={{ duration: 1.5, delay: 0.8 }}
                      className="h-full bg-white rounded-full shadow-[0_0_10px_white]"
                     />
                  </div>
                  
                  <div className="mt-8 pt-8 border-t border-blue-500/50 flex items-center justify-between">
                     <div className="flex items-center gap-2">
                        <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse"></div>
                        <span className="text-[10px] font-black uppercase tracking-widest">Optimal Path Calculation</span>
                     </div>
                  </div>
               </motion.div>

               <div className="bg-white p-6 rounded-[2rem] border border-slate-100">
                  <h4 className="text-sm font-black text-slate-900 mb-4 px-2">Skills Insights</h4>
                  <div className="space-y-4">
                     {[
                        { label: 'Adaptability', val: '95', color: 'emerald' },
                        { label: 'Team Fit', val: '88', color: 'blue' },
                        { label: 'Growth Speed', val: '72', color: 'amber' },
                     ].map(stat => (
                        <div key={stat.label} className="p-3 rounded-2xl bg-slate-50 space-y-2">
                           <div className="flex justify-between items-center text-[10px] font-bold text-slate-400 uppercase px-1">
                              <span>{stat.label}</span>
                              <span className="text-slate-900">{stat.val}%</span>
                           </div>
                           <div className="h-1 bg-slate-100 rounded-full overflow-hidden">
                              <div 
                                className={`h-full bg-${stat.color}-500 rounded-full`} 
                                style={{ width: `${stat.val}%` }}
                              ></div>
                           </div>
                        </div>
                     ))}
                  </div>
               </div>
            </div>
          </div>
        </div>
      )}
    </PageLayout>
  );
}
